// models/NZSIRegistration.js
import mongoose from 'mongoose';

const nzsiRegistrationSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    personalDetails: {
      firstName: { type: String, required: true },
      lastName: { type: String, required: true },
      gender: { type: String, required: true },
      email: { type: String, required: true },
      birthday: { type: String, required: true },
      occupation: { type: String, required: true },
      mobile: { type: String, required: true },
      landline: { type: String },
      address: { type: String, required: true },
      address2: { type: String },
      city: { type: String, required: true },
      postCode: { type: String, required: true },
      country: { type: String, required: true },
      state: { type: String },
      phonePlatform: { type: String },
      phoneModel: { type: String },
      hasGPS: { type: String },
      hasFacebook: { type: String },
    },
    emergencyContacts: {
      emergency1: {
        firstName: { type: String, required: true },
        lastName: { type: String, required: true },
        email: { type: String, required: true },
        mobile: { type: String, required: true },
        landline: { type: String },
        relationship: { type: String, required: true },
      },
      emergency2: {
        firstName: { type: String, required: true },
        lastName: { type: String, required: true },
        email: { type: String, required: true },
        mobile: { type: String, required: true },
        landline: { type: String },
        relationship: { type: String, required: true },
      },
    },
    medicalInfo: {
      hasMedicalCondition: { type: String, required: true },
      medicalCondition: { type: String },
      medications: { type: String },
      hasMedicationAllergies: { type: String, required: true },
      medicationAllergies: { type: String },
      hasFoodAllergies: { type: String, required: true },
      foodAllergies: { type: String },
      dietaryRequirements: { type: String },
      hasHealthFund: { type: String },
      healthFundName: { type: String },
      healthFundNumber: { type: String },
      hasAmbulanceCover: { type: String },
      medicareNumber: { type: String },
      medicarePosition: { type: String },
    },
    experience: {
      hasTraining: { type: String, required: true },
      recentTraining: { type: String },
      trainingDetails: { type: String },
      offRoadExperience: { type: String },
      experienceLevel: { type: String, required: true },
      confidenceAreas: { type: String },
    },
    motorcycle: {
      hireOption: { type: String, required: true },
      selectedMotorcycle: { type: String },
      ownBike: {
        make: { type: String },
        model: { type: String },
        year: { type: String },
        registrationNumber: { type: String },
        stateOrRegion: { type: String },
        odometer: { type: String },
        serviceUpToDate: { type: String },
        serviceIntention: { type: String },
        hasUnresolvedIssues: { type: String },
        issuesDetails: { type: String },
        hasComprehensiveInsurance: { type: String },
        fuelCapacity: { type: String },
        estimatedRange: { type: String },
      },
    },
    licenceDetails: {
      licenceValid: { type: String, required: true },
      licenceNumber: { type: String, required: true },
      licenceExpiryDate: { type: Date, required: true },
      licenceState: { type: String, required: true },
      licenceFilePath: { type: String },
    },
    equipment: {
      hydration: [{ type: String }],
      electronicEquipment: [{ type: String }],
      upperProtective: [{ type: String }],
      lowerProtective: [{ type: String }],
      bootBrand: { type: String, required: true },
      mechanicalRelated: [{ type: String }],
    },
    accommodation: {
      shirtSize: { type: String, required: true },
      accommodationPreference: { type: String, required: true },
      registerPartner: { type: String },
    },
    group: {
      ridingWithGroup: { type: String, required: true },
      groupMembers: { type: String },
      giftVoucherCode: { type: String },
    },
    terms: {
      agreeToTerms: { type: Boolean, required: true },
      termsAgreement: { type: String, required: true },
    },
    payment: {
      paymentOption: { type: String, required: true },
      totalPayment: { type: Number, required: true },
      paymentStatus: { type: String, default: 'Pending' },
    },
  },
  { timestamps: true }
);

export default mongoose.model('NZSIRegistration', nzsiRegistrationSchema);